module.exports = [
    'Acquario',
    'Amber Room',
    'A nóż widelec',
    'Appassionata',
    'Atelier Amaro',
    'Biesiada Opolska',
    'Bistro Słowacki',
    'Bistro Szarlotta',
    'Chapeau Bas',
    'Chłodna 15 by Wilamowski',
    'Dekant WineBar  Restaurant',
    'Dworek New Restaurant',
    'Eliksir',
    'Enoteka Pergamin',
    'Fedde Bistro',
    'Filipa 18 Food Wine Art',
    'Flavoria',
    'Góralska Tradycja',
    'Gościniec Ryński Młyn',
    'La Brasserie Moderne',
    'Lwia Brama²',
    'Meluzyna Restaurant  Wine',
    'Moo Moo SteakBurger Club',
    'Morskie Opowieści',
    'N31 RestaurantBar',
    'Nota_Resto by Tomasz Leśniak',
    'Olkuska 7 by Jarek Uściński',
    'Pałac Tłokinia',
    'Pawilon Towarzyski',
    'Pink Lobster',
    'Piwnica Rajców',
    'Pod Papugami Restaurant  Cocktail Bar',
    'Pracownia Smaku ORSO',
    'Quale Restaurant',
    'Restauracja à la carte ARŁAMÓW',
    'Restauracja AleGloria',
    'Restauracja Atmosphere',
    'Restauracja Arté',
    'Restauracja Art Deco Hotel SPA Dr Irena Eris Polanica Zdrój',
    'Restauracja Barracuda',
    'Restauracja Baryłka',
    'Restauracja Belle Epoque',
    'Restauracja BELVEDERE w Łazienkach Królewskich',
    'Restauracja Blow Up Hall 5050',
    'Restauracja BlueBell w Hotelu Natura Residence****',
    'Restauracja Bulaj Artur Moroz',
    'Restauracja Cristalino Kuchnia i Wino',
    'Restauracja Concept 13',
    'Restauracja Cafe Oranżeria',
    'Restauracja Cesarska',
    'Restauracja Copernicus',
    'Restauracja Cynamon',
    'Restauracja Ferula Hotel Bacówka RadawaSpa****',
    'Restauracja Gallo Nero',
    'Restauracja GierKrówka',
    'Restauracja Grande Cozze',
    'Restauracja Halka',
    'Restauracja Hashi Sushi',
    'Restauracja Jazz Bar',
    'Restauracja Joker',
    'Restauracja Karczma Lwowska',
    'Restauracja Krasnodwór',
    'Restauracja Klimatt',
    'Restauracja Lumière',
    'Restauracja Magiel Kulinarny',
    'Restauracja Magnifica',
    'Restauracja Miodowa',
    'Resteuracja Miodowa 8',
    'Restauracja Modrzewie Park Hotel',
    'Restauracja Monte - Carlo',
    'Restauracja Moonsfera',
    'Restauracja Pak Choi',
    'Restauracja Pałac Większyce',
    'Restauracja Pałacowa Hotelu Anders',
    'Restauracja Park Caffe',
    'Restauracja Pergola',
    'Restauracja Platter by Karol Okrasa',
    'Restauracja ProVita',
    'Restauracja Pod Fredrą',
    'Restauracja Polanka',
];
